version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8084:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Molly
      MYSQL_DATABASE: mysql